### PR TITLE
fix surf_dab on 'em haters

### PR DESCRIPTION
**Pull request by FrxztOfficial**

### CODE REVIEW

**Comment by krakow10** [comment]
@collborators please review all three maps when you merge this
```
441409904 - Clique - fixed last stage softlock
602067194 - Minecraft - fixed end stone texture
917104451 - Dab on 'Em Haters - fixed ramps
```

**Comment by numberss** [comment]
I'm gone for 3 weeks can't do it sorry quaternion man

**Comment by krakow10** [comment]
Next reviewer!  (just assigning people for the lulz, I'm not going to do this constantly)

**Comment by numberss** [comment]
this is fun but I think maybe pinging map council channel or getting a git Web hook might be the solution

**Comment by sirlolnoob** [comment]
all good

**Pull request merged**
