### PR TITLE
fixes and updates

### PR DESCRIPTION
**Pull request by 400bc**

### CODE REVIEW

**Comment by krakow10** [comment]
I don't really see any problem with the maps you want removed - maybe you could argue Summer Equinox but Concord?  I am fond of the map Macaroni and Cheese and would be sad to see it go...

**Comment by 400bc** [comment]
> I don't really see any problem with the maps you want removed - maybe you could argue Summer Equinox but Concord? I am fond of the map Macaroni and Cheese and would be sad to see it go...

You can keep Macaroni and Cheese if you want. Concord for me in my opinion personally I think doesn't play well on new physics if your going for fast times and there are a lot of trigger skips that shouldn't be there. I know I could fix the trigger skips and call it a day, but I would rather remake the map and edit some stages to make the better map rather than do a lazy edit and not fix my issues with the map. Summer Equinox is just a meme map that I made for a friend, doesn't feel good to play nor does it look good. I have no interest in editing or remaking the map so I would rather it just be removed - I just don't have the time to work/edit on maps anymore.

**Comment by krakow10** [comment]
I'm keeping Macaroni & Cheese and deleting the other four.  If other people want to fix the deleted maps they can get your blessing.

**Comment by krakow10** [comment]
Why are none of these on maptest?  Did you upload a new model when you finished making it?  Could you also please note which mapfixes need times to be wiped and which ones don't.

    11117945983 - Drewfc was being uncool
    11117954548 - Danger Noodle
    11117959400 - Leaf Beach
    11117961828 - Happy Gummy Bear
    11117968222 - Way Back When
    11117971522 - Colossus
    11419832052 - Bluebeat v2
    11420718853 - Sidus v2
    11416396856 - Yonkoma
    11416108691 - Very Long Map

**Pull request merged**
