### PR TITLE
4 AM anti resurfs

### PR DESCRIPTION
**Pull request by numberss**

### CODE REVIEW

**Comment by krakow10** [comment]
This will have to wait for world instances to become stable and be uploaded to the main game.  The pull request can hang around until then which is basically the reason I made this repository because I always forget about maps

**Comment by krakow10** [comment]
World instancing has been merged, please retest this and comment when it's ready

**Comment by numberss** [comment]
tested with 2 players and it works fine. new system of buttons on the ramp also works well. map is ready!

**Comment by numberss** [comment]
this also puts a roof on the map so faste times that go out of the map will need to be deleted

**Comment by krakow10** [comment]
The wrong file is edited here, I've replaced it with a new pull request (#46).  Either you or me could have edited this one using git but I did it this way instead.

**Comment by krakow10** [comment]
I decided to edit this one instead.

**Pull request merged**
